services:
  otel-lgtm:
    image: docker.io/grafana/otel-lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - lgtm-data:/data
      - lgtm-grafana:/var/lib/grafana

volumes:
  lgtm-data:
  lgtm-grafana: